export const dataList = [
  'Revenue',
  'Adjusted Close (Scaled)',
  'Cost of Revenue',
  'Gross Profit',
  'Gross Profit Ratio',
  'R&D Expenses',
  'General & Admin Expenses',
  'Selling & Marketing Expenses',
  'Selling, General, & Admin Expenses',
  'Other Expenses',
  'Operating Expenses',
  'Cost & Expenses',
  'Interest Income',
  'Interest Expense',
  'Deprecation & Amoritization',
  'EBITDA',
  'EBITDA Ratio',
  'Operating Income',
  'Operating Income Ratio',
  'Total Other Income Expenses Net',
  'Income Before Tax',
  'Income Before Tax Ratio',
  'Income Tax Expense',
  'Net Income',
  'Net Income Ratio,',
  'EPS',
  'EPS Diluted',
  'Weighted Average Shares Out',
  'Weighted Average Shares Out Diluted'
]
